site_name: MASArena
site_url: https://lins-lab.github.io/masarena
repo_name: LINs-lab/MASArena
repo_url: https://github.com/LINs-lab/MASArena

theme:
  name: material
  icon:
    logo: material/stadium-variant
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - toc.follow

markdown_extensions:
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Getting started:
    - Installation: quick_start/installation.md
    - Usage: quick_start/usage.md
    - Visualization: quick_start/visualization.md
    - Contributing: quick_start/CONTRIBUTING.md
  - System Architecture: system_overview.md
  - Extending: extending.md
  - Failure Attribution: failure_attribution.md
  - Tool Integration: tools/tool_integration.md
  - Supported: supported.md
  - AFlow Optimize: aflow_optimize.md